import '../../businesses/models/business.dart';

/// Per-business financial performance metrics used for the dashboard ranking list.
///
/// Pure-Dart value object — never persisted.
/// Carries both the [Business] entity and its computed financial metrics so the
/// UI can display name, category, and metrics from a single object.
class BusinessPerformance {
  const BusinessPerformance({
    required this.business,
    required this.invested,
    required this.netProfit,
    required this.roi,
  });

  /// The associated business entity.
  final Business business;

  /// Total capital invested into this business.
  final double invested;

  /// Net profit generated by this business: (Income + Dividends) − (Expenses + Taxes).
  final double netProfit;

  /// Return on investment percentage: (Net Profit / Invested) × 100.
  final double roi;

  /// Convenience getter — returns [business.id].
  int get businessId => business.id;
}
