import '../models/transaction.dart';

// ── Type-level semantic helpers ───────────────────────────────────────────────

/// Semantic classifiers on individual [TransactionType] values.
///
/// Centralising the "what is this type?" logic here keeps every formula in
/// [TransactionCalculator] readable and eliminates duplicated conditionals.
extension TransactionTypeClassifier on TransactionType {
  /// Returns `true` for types that generate operating revenue.
  ///
  /// Includes: Income, Dividend, Asset Sale.
  bool get isRevenueType =>
      this == TransactionType.income ||
      this == TransactionType.dividend ||
      this == TransactionType.assetSale;

  /// Returns `true` for types that reduce operating profit.
  ///
  /// Includes: Expense, Tax.
  bool get isCostType =>
      this == TransactionType.expense || this == TransactionType.tax;

  /// Returns `true` for capital injection events.
  ///
  /// Includes: Investment, Additional Investment.
  /// These add to the cost basis but do NOT count as revenue or profit.
  bool get isInvestmentType =>
      this == TransactionType.investment ||
      this == TransactionType.additionalInvestment;

  /// Returns `true` for capital-return events (money leaving the investment).
  bool get isWithdrawalType => this == TransactionType.withdrawal;

  /// Returns `true` for capital-expenditure events (asset purchases).
  bool get isAssetPurchaseType => this == TransactionType.assetPurchase;

  /// Returns `true` if this type participates in the Net Profit formula.
  ///
  /// Only revenue and cost types affect profit.
  /// Capital events (Investment, Withdrawal, Loan, Loan Repayment) are excluded.
  bool get affectsProfit => isRevenueType || isCostType;

  /// Returns `true` if this type moves real cash.
  ///
  /// Every type except [TransactionType.other] affects the cash flow statement.
  bool get affectsCashFlow => this != TransactionType.other;
}

// ── Collection-level financial engine ────────────────────────────────────────

/// Financial calculator extension on any [Iterable] of [Transaction] records.
///
/// Architecture principles enforced here:
/// • Every metric is computed on demand — nothing is stored.
/// • Each formula has a single, documented responsibility.
/// • All dashboard and provider metrics originate exclusively from this engine.
extension TransactionCalculator on Iterable<Transaction> {
  // ════════════════════════════════════════════════════════════════════════════
  // CAPITAL METRICS
  // ════════════════════════════════════════════════════════════════════════════

  /// Total equity capital deployed into the investment (cost basis).
  ///
  /// Formula: Σ(Investment) + Σ(Additional Investment)
  ///
  /// Withdrawals, loans, and operational flows are intentionally excluded.
  /// This value represents purely how much the investor has committed as
  /// equity capital.
  double calculateTotalInvested() {
    return where((t) => t.type.isInvestmentType)
        .fold(0.0, (sum, t) => sum + t.amount);
  }

  // ════════════════════════════════════════════════════════════════════════════
  // PROFIT METRICS
  // ════════════════════════════════════════════════════════════════════════════

  /// Operating profit generated by the investment.
  ///
  /// Formula: Σ(Income + Dividend + Asset Sale) − Σ(Expense + Tax)
  ///
  /// Capital events (Investment, Withdrawal, Loan, Loan Repayment) are
  /// intentionally excluded — moving capital in or out is not a profit or
  /// loss event; it only changes the capital structure.
  double calculateTotalReturns() {
    final revenue = where((t) => t.type.isRevenueType)
        .fold(0.0, (sum, t) => sum + t.amount);

    final costs = where((t) => t.type.isCostType)
        .fold(0.0, (sum, t) => sum + t.amount);

    return revenue - costs;
  }

  /// Canonical alias for [calculateTotalReturns].
  ///
  /// Used throughout the portfolio summary and dashboard under the label
  /// "Net Profit".
  double calculateNetProfit() => calculateTotalReturns();

  // ════════════════════════════════════════════════════════════════════════════
  // CASH FLOW METRIC
  // ════════════════════════════════════════════════════════════════════════════

  /// Net cash movement from the investor's perspective.
  ///
  /// **Inflows** (cash received by the investor or business):
  ///   Income, Dividend, Asset Sale, Loan
  ///
  /// **Outflows** (cash paid by the investor or business):
  ///   Investment, Additional Investment, Expense, Tax,
  ///   Withdrawal, Asset Purchase, Loan Repayment
  ///
  /// Corrections from the previous engine version:
  ///   • Withdrawal  → outflow  (capital leaves the investment)
  ///   • Loan        → inflow   (borrowed cash enters the business)
  ///   • Loan Repayment → outflow (repaying the loan costs cash)
  double calculateNetCashFlow() {
    final inflows = where((t) =>
            t.type == TransactionType.income ||
            t.type == TransactionType.dividend ||
            t.type == TransactionType.assetSale ||
            t.type == TransactionType.loan)
        .fold(0.0, (sum, t) => sum + t.amount);

    final outflows = where((t) =>
            t.type == TransactionType.investment ||
            t.type == TransactionType.additionalInvestment ||
            t.type == TransactionType.expense ||
            t.type == TransactionType.tax ||
            t.type == TransactionType.withdrawal ||
            t.type == TransactionType.assetPurchase ||
            t.type == TransactionType.loanRepayment)
        .fold(0.0, (sum, t) => sum + t.amount);

    return inflows - outflows;
  }

  // ════════════════════════════════════════════════════════════════════════════
  // ROI
  // ════════════════════════════════════════════════════════════════════════════

  /// Return on Investment expressed as a percentage of deployed equity capital.
  ///
  /// Formula: (Net Profit / Total Invested) × 100
  ///
  /// Returns 0.0 when no capital has been invested.
  double calculateROI() {
    final invested = calculateTotalInvested();
    if (invested <= 0.0) return 0.0;
    return (calculateNetProfit() / invested) * 100;
  }

  // ════════════════════════════════════════════════════════════════════════════
  // PORTFOLIO VALUE
  // ════════════════════════════════════════════════════════════════════════════

  /// Estimated current value of the portfolio position.
  ///
  /// Formula: Total Invested + Net Profit − Withdrawals − Asset Purchases
  ///
  /// Rationale:
  ///   • Withdrawals reduce value because capital has been returned to the
  ///     investor and is no longer working in the investment.
  ///   • Asset purchases are capital expenditures that consume the deployable
  ///     cash, reducing the remaining portfolio position.
  double calculatePortfolioValue() {
    return calculateTotalInvested() +
        calculateNetProfit() -
        calculateTotalWithdrawals() -
        calculateTotalAssetPurchases();
  }

  // ════════════════════════════════════════════════════════════════════════════
  // BREAKDOWN HELPERS
  // ════════════════════════════════════════════════════════════════════════════

  /// Gross income earned before deducting expenses.
  ///
  /// Includes: Income, Dividend.
  double calculateTotalIncome() {
    return where((t) =>
            t.type == TransactionType.income ||
            t.type == TransactionType.dividend)
        .fold(0.0, (sum, t) => sum + t.amount);
  }

  /// Total operating expenses (tax is reported separately).
  double calculateTotalExpenses() {
    return where((t) => t.type == TransactionType.expense)
        .fold(0.0, (sum, t) => sum + t.amount);
  }

  /// Total tax payments.
  double calculateTotalTaxes() {
    return where((t) => t.type == TransactionType.tax)
        .fold(0.0, (sum, t) => sum + t.amount);
  }

  /// Total capital returned to the investor via withdrawals.
  double calculateTotalWithdrawals() {
    return where((t) => t.type == TransactionType.withdrawal)
        .fold(0.0, (sum, t) => sum + t.amount);
  }

  /// Total capital expenditure on asset purchases.
  double calculateTotalAssetPurchases() {
    return where((t) => t.type == TransactionType.assetPurchase)
        .fold(0.0, (sum, t) => sum + t.amount);
  }
}

